[package]
name = "snakes_and_ladders"
version = "0.1.0"
author = ["Atharva Nalat <nalatatharva@gmail.com>"]
edition = "2025"

[dependencies]
rand = "^0.8.5"
iced = { version = "0.13.1", features = ["canvas", "tokio"] }
iced_runtime = "0.13.2"
